title: R Austausch
logo: https://storage.googleapis.com/dx-liip/production/storage/uploads/group/kt_zh.png
description: Der R-Austausch richtet sich an R Nutzer*innen in der Zürcher Kantonsverwaltung. Er dient als Plattform für den Wissensaustausch und der Vernetzung rund um die offene Statistiksoftware R. 
theme: minima
