title: R Austausch
logo: https://storage.googleapis.com/dx-liip/production/storage/uploads/group/kt_zh.png
description: "Kontakt: andrea.schnell@statistik.ji.zh.ch"
theme: minima

social_links:
    twitter: statistikZH

minima:
  date_format: "%d %-m, %Y"
  
future: true
